openapi: 3.0.2

info:
  version: 1.0.0
  title: Aspro CRM Integration
  description: Интеграция с Aspro CRM для звонков

servers:
  - url: 		'some-url'

paths:
  /update:
    post:
      operationId: sendDataAction
      summary: Обновить данные
      description: Действие обновления данных в CRM системе через POST запрос
      tags:
        - tomoru/call
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                leadID:
                  type: string
                  description: ID лида
                ActivityType:
                  type: string
                  description: Сфера деятельности
                  example: "Информационные технологии"
                IP-telephony:
                  type: string
                  description: IP-телефония
                  example: "Cisco"
                CRM:
                  type: string
                  description: CRM система
                  example: "Salesforce"
                CompanyHeadquarters:
                  type: string
                  description: Штаб компании
                  example: "Москва, Россия"
                NumberOfEmployees:
                  type: integer
                  description: Сколько человек
                  example: 500
                CompanyProducts:
                  type: string
                  description: Продукты компании
                  example: "Программное обеспечение, Консалтинг"
                AverageCheck:
                  type: number
                  format: float
                  description: Средний чек
                  example: 12000.50
                DealProduct:
                  type: string
                  description: Продукт сделки
                  example: "Корпоративное решение"
                InterestedIn:
                  type: string
                  description: Интересуется
                  example: "Новыми технологиями, Облачные сервисы"
              required:
                - leadID
      responses:
        200:
          description: Данные успешно отправлены
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Статус выполнения
        400:
          description: Неверный запрос
        500:
          description: Ошибка сервера
  
  /move:
    post:
      operationId: MoveDataAction
      summary: Перемещение лида по воронке
      description: Действие перемещения данных в CRM системе через POST запрос
      tags:
        - tomoru/call
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                leadID:
                  type: string
                  description: ID лида
                pipelineID:
                  type: string
                  description: ID воронки
              required:
                - leadID
                - pipelineID
      responses:
        200:
          description: Данные успешно отправлены
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Статус выполнения
        400:
          description: Неверный запрос
        500:
          description: Ошибка сервера

  /subscribe:
    post:
      operationId: subscribe
      summary: Подписаться на события
      tags:
        - tomoru/subscribe
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tomoruCallbackUrl:
                  type: string
              required:
                - tomoruCallbackUrl
      responses:
        200:
          description: Все ок
      callbacks:
        MakeACall:
          '{$request.body#/tomoruCallbackUrl}':
            post:
              summary: Прозвон клиентов
              description: Прозвон клиентов
              requestBody:
                content:
                  application/json:
                    schema:
                      allOf:
                        - $ref: 'https://api.tomoru.ru/openapi#/components/schemas/TomoruEvent'
                        - type: object
                          properties:
                            data:
                              type: object
                              properties:
                                field:
                                  type: string
                                  description: Имя клиента
                                lead_id:
                                  type: string
                                  description: ID сделки
                                  example: 123
                              required:
                                - name
                                - lead_id
                            
              responses:
                200:
                  description: Все ок
  /config-updated:
    post:
      operationId: configUpdated
      summary: Обновление конфига
      tags:
        - tomoru/config_updated
        - tomoru/bot_connected
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                config:
                  $ref: https://api.tomoru.ru/openapi#/components/schemas/TomoruConfig
                botId:
                  $ref: https://api.tomoru.ru/openapi#/components/schemas/botId
              required:
                - config
                - botId
      responses:
        200:
          description: Все ок
